import 'dart:async';
import 'dart:typed_data';

import 'package:flutter_soloud/flutter_soloud.dart';

import '../../core/audio/take_player.dart';
import 'soloud_audio_engine.dart';

/// Rejoue une prise, sur SoLoud.
///
/// **Aucune dependance de plus.** `loadMem` accepte, dit sa documentation,
/// "a simple WAV format sequence of manually generated bytes" : les
/// quarante-quatre octets d'en-tete ecrits par `PcmTake` suffisent donc a
/// rendre lisible ce que le micro a capture. Ni fichier, ni dossier, ni
/// permission de stockage.
///
/// **Elle ne passe pas par `AudioEngine`**, qui refuse volontairement de
/// charger quoi que ce soit (ADR-012). Les deux classes partagent la meme
/// bibliotheque native et la meme initialisation, pas la meme interface.
class SoloudTakePlayer implements TakePlayer {
  SoloudTakePlayer({SoLoud? soloud}) : _injecte = soloud;

  final SoLoud? _injecte;

  SoLoud get _soloud => _injecte ?? SoLoud.instance;

  AudioSource? _source;
  SoundHandle? _handle;
  Completer<void>? _fin;
  Timer? _minuteur;

  /// Marge ajoutee a la duree annoncee avant de declarer la lecture finie.
  ///
  /// Le moteur rend une duree calculee sur les echantillons ; entre elle et
  /// le dernier son sorti du haut-parleur, il reste le tampon de sortie.
  /// Rouvrir le micro trop tot lui ferait entendre la fin de la relecture,
  /// ce que l'ADR-008 interdit precisement.
  static const Duration marge = Duration(milliseconds: 120);

  @override
  Future<void> play(Uint8List wav) async {
    await stop();
    if (!_soloud.isInitialized) {
      await _soloud.init(sampleRate: SoloudAudioEngine.sampleRate);
    }
    final AudioSource source = await _soloud.loadMem('reecoute.wav', wav);
    _source = source;
    _handle = _soloud.play(source);

    final Completer<void> fin = Completer<void>();
    _fin = fin;
    // Un minuteur qui ne declenche aucun son : il ne fait qu'observer la fin
    // d'un son deja parti. L'interdiction du projet vise le declenchement,
    // pas l'observation.
    _minuteur = Timer(_soloud.getLength(source) + marge, () {
      unawaited(stop());
    });
    return fin.future;
  }

  @override
  Future<void> stop() async {
    _minuteur?.cancel();
    _minuteur = null;
    final SoundHandle? handle = _handle;
    final AudioSource? source = _source;
    _handle = null;
    _source = null;
    if (handle != null) {
      await _soloud.stop(handle);
    }
    if (source != null) {
      await _soloud.disposeSource(source);
    }
    final Completer<void>? fin = _fin;
    _fin = null;
    if (fin != null && !fin.isCompleted) {
      fin.complete();
    }
  }

  @override
  Future<void> dispose() => stop();
}

/// Le liseur par defaut, celui qui sonne pour de vrai.
TakePlayer defaultTakePlayer() => SoloudTakePlayer();
